language: android
env:
  matrix:
    - ANDROID_TARGET=android-27 ANDROID_ABI=armeabi-v7a
android:
  update_sdk: true  #Check for the updates each time you run the build.
  components:
      - platform-tools
      - tools
      - build-tools-28.0.2    #Build tool version
      - android-27            #targate api version

      # Additional components
      - extra-google-google_play_services
      - extra-google-m2repository
      - extra-android-m2repository

before_script:
  - chmod +x gradlew      #Grant permissions
  - android list targets
  - emulator -avd test -no-skin -no-audio -no-window &    #Start emulator
  - echo no | android create avd --force --name test --target $ANDROID_TARGET --abi $ANDROID_ABI    #Create AVD for given api

script:
  - echo "Travis branch is $TRAVIS_BRANCH"    #Print out which branch it is.
  - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"    #Print out pull request number.
  - adb devices                           #Display list of devices
  - adb shell input keyevent 82 &
  - ./gradlew connectedAndroidTest -PdisablePreDex --stacktrace   
  - ./gradlew test

before_install:
  - pip install --user codecov    #Install codecov

after_success:
  - codecov                       #Run codecov jkerjlhrd